# Generated by Django 4.2.1 on 2023-09-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Petshop')),
                ('rua', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
            ],
        ),
        migrations.AlterField(
            model_name='reservadebanho',
            name='diaDaReserva',
            field=models.DateField(verbose_name='Dia da Reserva'),
        ),
        migrations.AlterField(
            model_name='reservadebanho',
            name='email',
            field=models.EmailField(max_length=75, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='reservadebanho',
            name='nomeDoPet',
            field=models.CharField(max_length=50, verbose_name='Nome do PET'),
        ),
        migrations.AlterField(
            model_name='reservadebanho',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='reservadebanho',
            name='tamanho',
            field=models.IntegerField(choices=[(0, 'Pequeno'), (1, 'Médio'), (2, 'Grande')], verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='reservadebanho',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='reservadebanho',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=5, verbose_name='Turno'),
        ),
    ]
