# Generated by Django 4.2.5 on 2023-10-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_reservadebanho_petshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petshop',
            options={'ordering': ['id']},
        ),
    ]
